name: Sandbox Deploy
on:
  push:
    branches:
      - sandbox
jobs:
  build_and_deploy:
    container: node:13
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: sandbox

      - name: Install Dependencies
        run: npm install -g npm@7 && npm ci
        working-directory: ./theme

      - name: Build
        run: npm build:dev
        working-directory: ./theme

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: sandbox-deploy
          publish_dir: ./theme/dist
